version: '3'
services:
  app:
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0 # enable log/print display
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - .:/app